# Generated by Django 5.1.3 on 2024-12-12 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=255, null=True)),
                ('p_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('p_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('booked_on', models.DateField(auto_now=True)),
                ('doc_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.doctors')),
            ],
        ),
    ]
